
path: E:/Users/Kai 00/Documents/Master/Semester 3/AACV/Project
train: IDD10_shrunk/train # relative path
val: IDD10_shrunk/val # relative path
test: IDD10_shrunk/test # relative path

#Classes
nc: 10
names:
  0: car
  1: bus
  2: autorickshaw
  3: truck
  4: motorcycle
  5: rider
  6: person
  7: bicycle
  8: traffic sign
  9: traffic light