
path: /kaggle/input/idd-converted/IDD_converted
train: images/train # relative path
val: images/val # relative path

#Classes
nc: 15
names:
  0: car
  1: bus
  2: autorickshaw
  # 3: vehicle fallback
  4: truck
  5: motorcycle
  6: rider
  7: person
  8: bicycle
  # 9: animal
  10: traffic sign
  # 11: train
  # 12: trailer
  13: traffic light
  # 14: caravan