path: D:/Coding/Uni/traffic3/shrunk
train: train # relative path
val: val # relative path

#Classes
nc: 10
names:
  0: car
  1: bus
  2: autorickshaw
  3: truck
  4: motorcycle
  5: rider
  6: person
  7: bicycle
  8: traffic sign
  9: traffic light